### ISSUE TITLE
Item death drop chance

### ISSUE THREAD

**Issue by AMurkin** [nornagon/cdda-guide#1]
Item death drop chance is "0.00%" for some really rare items.
![image](https://user-images.githubusercontent.com/1931904/110255644-d2543f00-7fa5-11eb-8898-686605615120.png)

Maybe show something like "(< 0.01%)" when rounded result evaluates to 0.00%?
https://github.com/nornagon/cdda-guide/blob/599f4dbe3722044c9c5e0570fd59cf336f90bf4d/src/types/Monster.svelte#L433

**Comment by nornagon** [comment]
Thanks for the suggestion! done.
