### ISSUE TITLE
[feature request] add pinyin search rule to Chinese searching

### ISSUE THREAD

**Issue by tu10ng** [nornagon/cdda-guide#101]
It would be great to add pinyin search, which allows user to search without further choosing the Chinese word.

like when searching 'hacksaw'(in Chinese: '钢锯'), enter 'gangju' will do the search.
I am not sure whether it is easy or not.

Great tool by the way! helped me a lot when playing cdda.

**Comment by nornagon** [comment]
Hm, not sure. It might be possible with something like https://github.com/hotoo/pinyin? I'd want to be careful about not exploding the bundle size with a large module. Perhaps we could lazily load it only for the zh-* locales.

**Comment by nornagon** [comment]
Interesting thought! I could perhaps do the pinyin conversion when processing the item data, and store the pinyin version of each item name in the language JSON. That's a promising approach, I'll look into it.

**Comment by nornagon** [comment]
Okay, this should be working now. I tested a few things and it seemed to be working alright, but I don't read hanzi so my checks were somewhat rudimentary. I'd appreciate any further feedback :)

**Comment by nornagon** [comment]
(in case you're curious how this works, I now generate an additional locale data JSON file at e.g. https://github.com/nornagon/cdda-data/blob/main/data/0.G/lang/zh_CN_pinyin.json, this contains the pinyin versions of all the translations of item names. It turns out to only be around 100 KB gzipped, which is about 2% of the size of the rest of the data, so totally manageable :))

**Comment by tu10ng** [comment]
can you show me some example? i have tried but it seem not working, maybe i am not using it correctly

**Comment by nornagon** [comment]
Try refreshing a couple of times. The code is cached in your browser so it
needs a refresh to update. But searching for “gj” for instance brings up
hacksaw:


-- 

j

**Comment by nornagon** [comment]
Try refreshing a couple of times. The code is cached in your browser so it
needs a refresh to update. But searching for “gj” for instance brings up
hacksaw:

![IMG_9570](https://github.com/nornagon/cdda-guide/assets/172800/dc3f3019-d880-4b6a-aa2f-4db7af2ba670)

**Comment by tu10ng** [comment]
the pinyin search is working correctly and very usefull!

the problem is that the original 'search by Chinese characters' isn't working right now (for both ch_CN and ch_TW)

![image](https://github.com/nornagon/cdda-guide/assets/47939948/d581f1f4-712a-40b0-9266-82c43f0c40b5)
