### ISSUE TITLE
Random page link doesn't work when opening a new page with cmd+click or middle-click

### ISSUE THREAD

**Issue by Nina667** [nornagon/cdda-guide#102]
A random page always yields condensed milk
![IMG_20220903_030201](https://user-images.githubusercontent.com/112735690/188247763-bde98fdc-6584-414a-86b4-a055cb4c1dc4.jpg)

**Comment by Nina667** [comment]
Corrected:

The function works a little weird, when you open a new window always condensed milk in general all works great, thanks!

**Comment by Nina667** [comment]
I apologize in advance for my English, but I hope you understand.

**Comment by Nina667** [comment]
Corrected 

When opening a new window if you use the translator

**Comment by nornagon** [comment]
Ah, yeah it makes sense that it wouldn't work properly when opening a new page! I'll reopen this to track it.
