### ISSUE TITLE
doesn't show light industrial location as a source for welding rods

### ISSUE THREAD

**Issue by nornagon** [nornagon/cdda-guide#104]
https://nornagon.github.io/cdda-guide/#/item/welding_rod_steel

**Comment by Raikiri** [comment]
Is it actually just 14% though? I feel like I find welding rods much or often in light industries. It also shows megastore welding rods is at 48.95%, when in reality every megastore raid results in literally thousands of welding rods. Admittedly I can be biased by the fact that from gameplay perspective brazing rods/welding rods/welding wire are all kinda the same thing (which is not strictly true), but I still feel like it's much more than 48% in practice.
