### ISSUE TITLE
[feature request] add dockerimage

### ISSUE THREAD

**Issue by DoiiarX** [nornagon/cdda-guide#105]
Could author provide a docker image to build the web locally?
i hope to install the app locally.because browser will clear local file of items' json while using.
At that case,only enlish version cloud use,and the web in other language need loading online. 

thanks.

**Comment by nornagon** [comment]
I don't think a Dockerfile makes sense for this project. I'm not sure what you mean by "browser will clear local file of items json"—the items json should be saved in the cache and the app should function well offline. If that's not the case, I'd appreciate you sharing more details about what's not working properly in that situation!

When running the app locally, it will still fetch the CDDA data from the internet via https://github.com/nornagon/cdda-data, so I'm not sure this is what you want, but you can download and build the app on your machine if you like. You'll need Node.js and Yarn installed:

```
$ git clone https://github.com/nornagon/cdda-guide
$ cd cdda-guide
$ yarn
$ yarn dev
```
