### ISSUE TITLE
More detail of offline usage of other language.

### ISSUE THREAD

**Issue by DoiiarX** [nornagon/cdda-guide#106]
i have noticed at #105 that 
> At that case,only english version could use, and the web in other language need loading online.

To reproduce this error,the step is below:

step1:
visit the website `https://nornagon.github.io/cdda-guide/#` and there is a button `"installable"` to install the web as app.
![image](https://user-images.githubusercontent.com/25550075/189815048-e3861936-bef6-4b5c-93a8-853225b23d28.png)
click the web and the app is installed correctly.
![image](https://user-images.githubusercontent.com/25550075/189815102-b539fe02-e224-47f0-8111-35a55408ffee.png)

step2:
open the app and visit other language to have items json loaded.
![image](https://user-images.githubusercontent.com/25550075/189815384-74849283-f58c-4f1d-ac9a-f6fc2b55bc1c.png)

step3:
close the app and close my net. reopen the app again.
![CopyQ TTVcem](https://user-images.githubusercontent.com/25550075/189816865-a292dbea-da9f-45b7-aa29-aa6d775d6d0b.png)
as you can see, the english web loaded and the subpage of items work well.
![CopyQ dabtxi](https://user-images.githubusercontent.com/25550075/189816926-c89764c2-30c5-4a27-9fb6-e2418a63af80.png)
but the items of other language couldn't loaded from cache.

---

it sounds like which app installed is only about the web from `https://nornagon.github.io/cdda-guide/#`.
and the other pages such as `https://nornagon.github.io/cdda-guide/?lang=zh_CN` is not cached.
yeah,not only pages but items json of other language is not allowed to use offline

To further testing,i try to install the app in `https://nornagon.github.io/cdda-guide/?lang=zh_CN`.But when you visite other language there isn't a button such as `"installable"` to installed it.
![image](https://user-images.githubusercontent.com/25550075/189817463-72fc988b-9e56-42c9-9685-caf4648560cb.png)

So,i installed it by `seting >>Application>>install this web as app`.
![image](https://user-images.githubusercontent.com/25550075/189817780-9276e04b-ec4b-44d5-a41f-130bf934e411.png)

But what i installed is also `https://nornagon.github.io/cdda-guide/#`

So i also can't solve the problem.

i think if there is a page like `https://nornagon.github.io/cdda-guide/zh_CN/#`,maybe it could install the web as app in other language
to allowed user to use it offline.

---

What's more, what make me want to  get a docker image is that people in our country cann't connect to github drectly.
The government build GFW(Stand for the Great Fire Wall of china) to limit ours visit.

So all we need a vpn(such as clash) to connect github.com. Also somebody use project such as https://github.com/521xueweihan/GitHub520 to edit host to avoid GFW. But it not works always.

So...in our country, many people couldn't use cdda-guide.
https://tieba.baidu.com/p/7956117527?pn=1
![image](https://user-images.githubusercontent.com/25550075/189820377-8ccf03d2-80e9-442a-a6ff-8a302b24466b.png)

in the screenshot the guys said he have spend more than 20min to loading it.
![image](https://user-images.githubusercontent.com/25550075/189820597-e6a02b5e-35ce-4c95-9ffd-07cb99a57b28.png)

there is only the programers or young people which known how to use vpn and pay for it could use cdda-guide, and the normal game player couldn't visit.

I am skilled in python not java. So that i want to build a image web but i don't know how to build it.
so i asked for a docker image so that i could deploy it simply.

i have build a dockfile by my own but it not works.
it will refresh in few seconds and at some times there is nothing.
files such as `main.ts` is not loading correctly .

![image](https://user-images.githubusercontent.com/25550075/189822082-c4da18ab-23ae-409c-adcb-b666aeaf9117.png)
```dockerfile
FROM node:latest

WORKDIR /app

RUN apt-get update && apt-get install -y git && \
	git clone https://github.com/nornagon/cdda-guide
RUN cd ./cdda-guide && npm install --legacy-peer-deps && yarn

ENV PORT=3000
EXPOSE $PORT

WORKDIR /app/cdda-guide
CMD [ "yarn", "dev","--host","0.0.0.0"]
```
thanks for your reading.

**Comment by nornagon** [comment]
Yeah, we're not properly saving the translations offline. That's a bug and should be fixed.

As from loading from behind the GFW, I don't see how that's possible because all the data is hosted on GitHub behind raw.githubusercontent.com, which I think is blocked?

**Comment by nornagon** [comment]
I've made a change that should save the translations offline. Let me know if the issue persists.
