### ISSUE TITLE
[Feature request] Link integrated armor to/from mutations

### ISSUE THREAD

**Issue by Terrorforge** [nornagon/cdda-guide#109]
Plenty of mutations grant one or more pieces of integrated armor, and it's kind of impossible to evaluate what they do without looking at that armor, but the HHG currently has no easy way to see which mutation is tied to which armor.

I suggest a "Grants:" field or something that links to the armor from the mutation entry. Should be easy enough, as the json includes a direct reference, e.g. [Furry](https://nornagon.github.io/cdda-guide/#/mutation/FUR):

`  "integrated_armor": [
    "integrated_fur"
  ]`

And then ideally the integrated_fur item would also have a corresponding "Granted by:" field that links back to the mutation.

**Comment by nornagon** [comment]
Done :)

**Comment by Terrorforge** [comment]
Thank you!
