### ISSUE TITLE
[Feature Request] Support for Cataclysm: Bright Nights

### ISSUE THREAD

**Issue by BlueManedHawk** [nornagon/cdda-guide#112]
I'm surprised that there doesn't seem to already be a request filed for this, but i'd like to request support for the Bright Nights fork of C:DDA.  I have no idea what the internals of the two games are like or how different the storage of the data is between them, so i do apologize if this is an unreasonably large ask.

**Comment by nornagon** [comment]
Thanks for the request! I'm not interested in supporting BN, but anyone is welcome to make a fork of the Guide targeted at BN.
