### ISSUE TITLE
Override duplicated recipes (per CDDA's behavior), do not duplicate entries

### ISSUE THREAD

**Issue by RenechCDDA** [nornagon/cdda-guide#113]
CDDA **overrides** duplicated recipe entries. If two recipes have the same id *and no suffix*, then the values from whichever is read later will be used. HHG displays them as two separate entries - perhaps useful to find a rare bug if a contributor is looking, but also erroneous! 

As of this writing there is a duplicated recipe for welding kit, which results in the display of two recipes (the same) on HHG, which is how I learned of this discrepancy. ( https://nornagon.github.io/cdda-guide/#/item/welding_kit ) Although the recipe does not differ in this circumstance, it could in others. (I believe, but don't quote me on this, that this is how recipe adjustments in mods work as well - it simply loads the mod recipes *afterwards* and overwrites whatever is already there!)

This *shouldn't* really come up a lot, but figured I'd make an issue about it. It's the only thing I've ever found wrong on the site!

**Comment by nornagon** [comment]
Thanks for the keen eye! I'll look into fixing this.

**Comment by RenechCDDA** [comment]
No longer relevant, https://github.com/CleverRaven/Cataclysm-DDA/pull/72220 cleaned this up.

**Comment by nornagon** [comment]
Ahaha, the old "wait for the problem to go away" worked again :winning:
