### ISSUE TITLE
Fix incorrect volume in items with `count`

### ISSUE THREAD

**Issue by GuardianDll** [nornagon/cdda-guide#115]
We open a HHG, open a cement:
![image](https://user-images.githubusercontent.com/67688115/217655828-fee64c70-cb51-4738-8dd1-76180645f418.png)

then we open the game, spawn one unit of cement, and see this:
![image](https://user-images.githubusercontent.com/67688115/217655957-f7c449a9-21f4-463b-9c38-38facb09d729.png)

As you may expect, 0.25 L != 0.01 L
The reason of this is the `count` field, and how the game works with it - if the item has this field, it will divide the `volume` definition on it. We want to get rid of it, but its a long work, and HHG show the wrong info now

**Comment by nornagon** [comment]
ooh, good catch! Thanks for letting me know, I'll fix it up.

**Comment by nornagon** [comment]
Should be fixed now!
