### ISSUE TITLE
Ability to see what a given mutation is cancelled by

### ISSUE THREAD

**Issue by Raikiri** [nornagon/cdda-guide#116]
Currently there's no way to search for a list of mutations (or CBM's!) that cancel any given mutation by conflicting with it. It would be very useful to create such list.

**Comment by nornagon** [comment]
Thanks! Done :)

**Comment by Raikiri** [comment]
Awesome! But is it possible to also build a list of CBM's that cancel a given mutation?

**Comment by nornagon** [comment]
Ah, good catch! Also done!

**Comment by Raikiri** [comment]
Gigachad! Can't wait for the build to go through!

**Comment by Raikiri** [comment]
From user's perspective you can "cancel" a mutation not only by acquiring mutation that actually "cancels" it, but also by acquiring any other mutation of the same Type, since they're mutually exclusive. So if one wants to cancel their "Paws(-3)", there's no mutations that "Cancel" it directly, but there's lots of other mutually exclusive options in the HANDS type: https://nornagon.github.io/cdda-guide/#/mutation_type/HANDS , so for an end user cancelling by "Cancels" and mutual exclusivity inside of a given Type are basically the same thing, even though from code perspective they're completely different.

I wonder if we can or should add other mutations of the same Type into the "Cancelled by" list.
