### ISSUE TITLE
Color mutations according to their point cost

### ISSUE THREAD

**Issue by Raikiri** [nornagon/cdda-guide#117]
It's crucial to see in a list for any given category which mutations are treated by the game as "positive", "neutral" and "negative" for the sake of knowing which ones can be gained depending on genetic damage levels. Currently it requires opening a category, such as this one: https://nornagon.github.io/cdda-guide/#/mutation_category/CHIMERA and then opening every single mutation to see its point cost. It would be great if they were color-coded to see that at a glance, probably as red/purple/green (same as in-game).

**Comment by nornagon** [comment]
by 'in-game' I think you mean this screen?

![Screen Shot 2023-02-24 at 2 47 32 PM](https://user-images.githubusercontent.com/172800/221312214-a447c073-e042-40e9-97e6-9c763d8fcaf5.png)

if so, done :)

**Comment by Raikiri** [comment]
Wow, that's great!

**Comment by Raikiri** [comment]
Can we also add the same point cost display to other views, such as this one? https://nornagon.github.io/cdda-guide/#/mutation_type/CLAWS

**Comment by nornagon** [comment]
yep, done! let me know if you spot anywhere else that needs it.

**Comment by Terrorforge** [comment]
I just wanted to pop in and say that I just noticed this change, as well as the new GUI thing that shows how mutations progress, and say that I love it. Thank you very much.

**Comment by Raikiri** [comment]
Wow I also noticed that mutations are now shown in chains. Love these types of changes!

**Comment by nornagon** [comment]
@Terrorforge yep, I just copied the logic that the game uses to show a color :) I think it makes the most sense to match what's in-game; having the points shown also lets you use that to determine whether it's a "good" or "bad" mutation for the purposes of the mutation mechanics.

@Raikiri I have some more thoughts about how I'd like to evolve these UIs over time, but for now this was the simplest change I could think of that still added value :)

**Comment by nornagon** [comment]
Also @Raikiri, with the next build we should be showing point cost everywhere there's a mutation link, including search results and bionic pages.
