### ISSUE TITLE
Show consume_drug info

### ISSUE THREAD

**Issue by nornagon** [nornagon/cdda-guide#119]
https://www.reddit.com/r/cataclysmdda/comments/11ag2uu/a_guide_to_how_the_new_mutation_system_actually/ suggests opening "Raw JSON" to check mutagen vitamin levels. This should be shown on the item screen.

It's a bit complex because these values are behind the consume_drug use_action, which is quite a complex use_action, so we might not want to display it inline along with other usages.

e.g. https://nornagon.github.io/cdda-guide/#/item/vitamins, https://nornagon.github.io/cdda-guide/#/item/mutagen_elfa

**Comment by Raikiri** [comment]
Ah, just noticed this issue after creating https://github.com/nornagon/cdda-guide/issues/120

> suggests opening "Raw JSON" to check mutagen vitamin levels. This should be shown on the item screen.
that's my article btw :) just so you know, from user's perspective any information that can be extracted from JSON of the currently viewed entry is a nice to have QoL. However, being able to see relationships _between_ entries is where this guide is invaluable, So things like "Cancelled by" that are not directly stored in the json are irreplaceable for the user.

**Comment by nornagon** [comment]
I ended up just displaying this inline in the usage line for now; I might break it out later. Also piped it into the vitamin display screen, so e.g. https://nornagon.github.io/cdda-guide/#/vitamin/mutagen shows a list of items which contain mutagen.

**Comment by Raikiri** [comment]
Ah, I see you're also showing "consume with syringe" which can be very handy. Thanks!

What does "Rate: 1h" mean? Does it mean that its level decays at 1 unit per hour? Then I guess rate should be in 1/h and not in h units.

**Comment by nornagon** [comment]
It's straight from the JSON. See https://github.com/CleverRaven/Cataclysm-DDA/blob/67857e9f51e44db369a8d06c7f45bbd4ab46ae32/src/vitamin.h#L78-L79

         * Usage rate of vitamin (time to consume unit)
         * Lower bound is zero whereby vitamin is not required (but may still accumulate)

Admittedly "Rate" is probably not the best label here :D
