### ISSUE TITLE
Severe lag on livesearch in Firefox

### ISSUE THREAD

**Issue by GGgatherer** [nornagon/cdda-guide#12]
As said [here](https://github.com/nornagon/cdda-guide/issues/6#issuecomment-813021529), I'm seeing consistent lagging while filling search field. Win7 64, firefox 78.9.0esr. Attached profiling is showing me trying to search for "heavy duty frame" (without quotes, of course), which takes about 30 seconds to complete.

[profile.zip](https://github.com/nornagon/cdda-guide/files/6270878/profile.zip)

Suggested easy fix: add 0.5s-1s wait-after-last-keypress timer to search. We don't usually need to see each and every item fitting `left(what we actually search for, N)` for each and every N

**Comment by nornagon** [comment]
Thanks for the profile! It looks like the browser is spending the majority of the time in the search system, which is just stock [fuse.js](https://fusejs.io/). It seems to perform OK on Firefox on my machine, with search updates taking around 50ms, while that profile indicates around 700ms for a search (🙀 ). Are you using a low-powered machine?

Adding a ratelimit seems reasonable.

**Comment by natovan** [comment]
Same here. And I have a reasonable machine. Didn't know you have to had a mining rig to run search on a website

**Comment by GGgatherer** [comment]
Well it *is* old - Core I5-750 - but it's not *that* weak. And I never had such severe lags on other sites.

**Comment by nornagon** [comment]
@GGgatherer I've tweaked some stuff to make searching a little faster. Would you mind trying again? I'm still not able to reproduce your results unfortunately :(

**Comment by nornagon** [comment]
I've now swapped out the search engine for something that's quite a bit more performant (and I think more accurate too!). I'm closing this for now as I haven't heard any new reports, but happy to continue investigating if this continues to be an issue.
