### ISSUE TITLE
Make it easier to find mutation trees

### ISSUE THREAD

**Issue by Raikiri** [nornagon/cdda-guide#121]
When choosing which mutation tree to go, it's very useful to be able to navigate to a page like this one : https://nornagon.github.io/cdda-guide/#/mutation_category/CHIMERA or this one https://nornagon.github.io/cdda-guide/#/mutation_category/LUPINE

However, currently the only way I know how to get there is to search for any mutation of a given tree, for example I know that Chimera has a Fangs https://nornagon.github.io/cdda-guide/#/mutation/FANGS and from there click the "Chimera" link.

I'd like to be able to simply type "Chimera" in the search box and navigate to the page directly.

Also this page https://nornagon.github.io/cdda-guide/#/mutation is currently very cluttered. I think maybe it's better to make each tree into a collapsible frame or maybe just make it a link to a page containing actual list of its mutations, because currently it's very cumbersome to simply see what mutation trees are there in the game and even how many of them there are. Ideally I'd like to a see a list of all existing mutation trees on one screen.

**Comment by nornagon** [comment]
FYI, it's not linked anywhere but https://nornagon.github.io/cdda-guide/#/mutation_category will show you all the categories. It's reasonable to put those into search results.

**Comment by Raikiri** [comment]
> https://nornagon.github.io/cdda-guide/#/mutation_category
Right. Maybe it's best to link this page from the front page rather than to https://nornagon.github.io/cdda-guide/#/mutation ?

**Comment by nornagon** [comment]
hm, well https://nornagon.github.io/cdda-guide/#/mutation actually just includes every mutation category page directly (as well as the mutations with no category). I think the best thing to do is just put mutation categories in the search results. It's true that #/mutation is quite long, but I don't feel like that's a huge issue right now, and #/mutation_category is there for when you really want to see the full list.

**Comment by Raikiri** [comment]
My issue is just with the discoverability of #/mutation_category -- as you said, nothing links on it and nothing even hints that it exists. So if somebody wants to plan their mutation path, they would struggle with the same problem.

Probably just including mutation tree names into the search results would solve a large part of this problem, but I'd still wish there was a way to navigate to #/mutation_category from the front page somehow (not sure how).

**Comment by nornagon** [comment]
Thought about this for a while, I still don't feel like /mutation_category is useful enough to highlight separately from /mutation. Though I could imagine reworking the /mutation catalog UI in the future, I'm going to close this for now as I don't specifically plan to work on it.
