### ISSUE TITLE
feature request: ability to specify a search string via url

### ISSUE THREAD

**Issue by esotericist** [nornagon/cdda-guide#13]
much the same way you can specify an exact result with `#/item/flashlight`, it would be helpful if we had some url target that would specify a search, so that we can set up a bot link on the official dev discord that links to search results.

example use case (exact syntax match not needed):
![image](https://user-images.githubusercontent.com/1569754/113936253-5e77a300-97ac-11eb-8c92-ee52c6ea2edb.png)

how we construct the command on the bot side:
![image](https://user-images.githubusercontent.com/1569754/113936349-80712580-97ac-11eb-9e33-b999c8245e39.png)

**Comment by nornagon** [comment]
This is now available as `#/search/...`, e.g. https://nornagon.github.io/cdda-guide/#/search/kevlar

**Comment by esotericist** [comment]
belatedly: i really appreciate the fact the url auto-updates as you change your search term. that's a great touch.

do you happen to have any preferences/dispreferences on the bot command for the official dev discord server? current leading thought is `-hguide <x>`

**Comment by nornagon** [comment]
i think either `-guide` or `-hhg` would be great :)
