### ISSUE TITLE
Most entries are broken

### ISSUE THREAD

**Issue by Raikiri** [nornagon/cdda-guide#130]
https://nornagon.github.io/cdda-guide/#/item/cookbook_human

Pages such as this one display an error instead of item information

**Comment by nornagon** [comment]
Yep, I’m aware and working on a fix. Thanks for the report!

**Comment by Raikiri** [comment]
Yeah I realized that something broke big time, not just books. I guess I just reported the first thing I encountered.

**Comment by nornagon** [comment]
Should be fixed with 78dde9e, assuming it passes the tests and gets rolled out :)

**Comment by nornagon** [comment]
This turned out to be the issue: https://github.com/CleverRaven/Cataclysm-DDA/pull/64402, but it exposed some inconsistencies in how i was handling top-level item groups vs inline item groups, which i've now hopefully resolved.
