### ISSUE TITLE
[bug] armored monster shows armor 0

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#132]
The guide says mon_feral_marine_bayonet has 0 armor, but JSON says  `"armor": { "bash": 4, "cut": 6, "bullet": 10  }`

https://cdda-guide.nornagon.net/monster/mon_feral_marine_bayonet

![image](https://user-images.githubusercontent.com/52621858/235004673-cc8fd2cc-4773-4c91-8994-be77ba1d0c16.png)

The commit that changed how C:DDA parses monster definitions https://github.com/CleverRaven/Cataclysm-DDA/commit/651a0c66389a4502534507d90aab3fd3cab8f9f6

**Comment by nornagon** [comment]
Thanks, yeah the [tests](https://github.com/nornagon/cdda-guide/actions/runs/4792669528/jobs/8524416160) caught this, just haven't had time to fix it up yet. I should be able to get to it today or tomorrow though :)
