### ISSUE TITLE
seed_data doesn't account for default values

### ISSUE THREAD

**Issue by RenechCDDA** [nornagon/cdda-guide#137]
e.g. https://cdda-guide.nornagon.net/item/seed_spurge

When harvesting a planted seed it actually gives spurge(flowers) **and** spurge seeds (HHG claims it produces only flowers and withered plants). This is because `seeds` is an optional value in the seed_data array, which *defaults* to true. So even though it's not defined in spurge's json, it is still true.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#seed-data

**Comment by nornagon** [comment]
huh, interesting ... no plant in the game seems to set "seeds" to false. I guess it doesn't hurt to add the seed itself to the harvest list, but it seems a little redundant if it's never not the case!

**Comment by nornagon** [comment]
I'm also a little confused about the apparent redundancy between seed_data and harvest groups on the furniture version of the plant: https://cdda-guide.nornagon.net/furniture/f_flower_spurge

seems like that ought to be cleaned up upstream!
