### ISSUE TITLE
(Feature request) Millable information

### ISSUE THREAD

**Issue by RenechCDDA** [nornagon/cdda-guide#138]
Some food (mostly grains) can be milled. It would be nice if HHG displayed this information prominently, like it does for brewing/fermentation. 

Example: https://cdda-guide.nornagon.net/item/wild_rice --> https://cdda-guide.nornagon.net/item/dry_wild_rice
```
  "milling": {
    "into": "dry_wild_rice",
    "conversion_rate": 5
  },
```

and per json_info.md:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#datajsonitems-jsons
```
"milling": {                                 // Optional. If given, the item can be milled in a water/wind mill.
  "into": "flour",                           // The item id of the result of the milling.
  "conversion_rate": 1.0                     // Conversion of number of items that are milled (e.g. with a rate of 2, 10 input items will yield 20 milled items).
},
```

**Comment by nornagon** [comment]
Done, thanks for the suggestion!
