### ISSUE TITLE
Add a catalog on the front page to browse proficiencies

### ISSUE THREAD

**Issue by cosmo-naut** [nornagon/cdda-guide#140]
Currently proficiencies can be found via recipes that require them.
Individually, they have [pages which can be viewed](https://cdda-guide.nornagon.net/proficiency/prof_preservation)
However, they do not have a catalog that allows to browse for them and they [can not be searched for directly](https://cdda-guide.nornagon.net/search/Food%20preservation).

**Comment by nornagon** [comment]
Yeah, I was just thinking about this today. I'll add it.

**Comment by cosmo-naut** [comment]
I actually tried that tismorning but by adding an extra slash `https://cdda-guide.nornagon.net/proficiency/` it took me back to the home page

**Comment by cosmo-naut** [comment]
Here are some related nice to haves:
- proficiency catalog groups by skill
- proficiency catalog indents proficiencies below their pre-requisites
- individual proficiency pages link to pre/post-requisites
