### ISSUE TITLE
Hide the real stats of the ancient red dragon

### ISSUE THREAD

**Issue by Fris0uman** [nornagon/cdda-guide#143]
So this is a bit of a silly request and it might not be worth the effort but it'd be nice if hhg could hide the stats of the ancient red dragon.

The only purpose of that monster is to be a jumpscare, it doesn't help anyone to get the stats before seeing it in game and it kills the only reason this monster has to be in the game.

**Comment by nornagon** [comment]
Heh, alright. Done in https://github.com/nornagon/cdda-guide/commit/a921501f70b22c2af64ddbb182238015065e7107. I hid them behind a spoiler warning, which I think is a reasonable balance.

**Comment by Fris0uman** [comment]
Very nice, Thanks!
