### ISSUE TITLE
Search function Issue

### ISSUE THREAD

**Issue by estebandellasilva** [nornagon/cdda-guide#144]
i noticed an issue with the search function.

when i try searching for certain items it seems not all items of that  type are listed
in my case CBM
![image](https://github.com/nornagon/cdda-guide/assets/89189872/ca2358ee-0c9b-4a32-8611-1bfc20ee7e5a)
![image](https://github.com/nornagon/cdda-guide/assets/89189872/a96231e2-a47f-40b6-910d-193b9e414597)

If you search for CBM you dont get all the CBMs which are available in the game just a small amount
there are other cbms missing like the subdermal carbon filament and so on

**Comment by nornagon** [comment]
There is a limit to the number of results shown, which I think is what you’re observing. The full list of CBMs is on the item page under bionics: https://cdda-guide.nornagon.net/item

I don’t think lifting the search result limit count is a good solution to this problem, but maybe there could be some indication that there are more results than are shown.

**Comment by nornagon** [comment]
Turns out it was pretty easy to make it possible to view _every_ result when requested, using similar logic to other pages which show "See XYZ more...". So this should be fixed now :)
