### ISSUE TITLE
Display piercing damage instead of cut for SPEAR and STAB flagged weapons

### ISSUE THREAD

**Issue by ErisShrugged** [nornagon/cdda-guide#15]
Per the discussion at https://discordapp.com/channels/598523535169945603/598523535169945607/832257276696985620, these flags apparently cause cut damage listed in the JSON for the weapon to be treated by the game as piercing and displayed as such when viewing the weapons ingame. The Guide mirroring this behavior would reduce confusion.

**Comment by nornagon** [comment]
not sure if github sends you an email when i close something with a commit but hey @ErisShrugged this is fixed now :)

**Comment by ErisShrugged** [comment]
It just crossed my mind that I could reply here and say 'yay!' or something! I did get an email when the issue was closed, as well.

So, yay! :D
