### ISSUE TITLE
BUG: utility exoskeleton spawns are not displayed in the guide

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#150]
[ICE utility exoskeleton](https://cdda-guide.nornagon.net/item/ice_utility_exoskeleton_off) and [battery powered utility exoskeleton](https://cdda-guide.nornagon.net/item/utility_exoskeleton_off) spawn in a ["portal room" lab finale, a military base and Trans-Cost logistics](https://github.com/search?q=repo%3ACleverRaven%2FCataclysm-DDA%20ice_utility_exoskeleton_off&type=code):

![image](https://github.com/nornagon/cdda-guide/assets/52621858/4ee0348f-7038-4c2d-a3a1-aa9bc4bdc70a)

but for some reason this is not mentioned in the guide:

![image](https://github.com/nornagon/cdda-guide/assets/52621858/099f60dd-5cd2-4f22-9f7a-e193db035045)
![image](https://github.com/nornagon/cdda-guide/assets/52621858/00d775f1-e072-4d34-88e3-e7f700f74c55)

**Comment by nornagon** [comment]
Likely because those locations are specifically excluded from the loot tables. (They are visually large in the list, and it is a bit fun to have some "extra secret" places, I think.)

**Comment by nornagon** [comment]
looked into this in more detail:
- `lab_finale_1level` is only ever inserted by C++ code, it doesn't have an associated `overmap_special` object. So HHG doesn't know what location the mapgen is associated with, and thus ignores it.
- `mil_base` and `Lab_CARGO_Surface` are on the [ignore list](https://github.com/nornagon/cdda-guide/blob/a49911e081a0428d05d94dff824acc8c99f99ac8/src/types/item/spawnLocations.ts#L233-L248)

so all the places this can spawn in are either not JSONized or are specifically ignored by HHG :)
