### ISSUE TITLE
no reads, zero mbs, non existant inventory

### ISSUE THREAD

**Issue by Miami-notgoodwithc** [nornagon/cdda-guide#152]
no matter what build ive put in nothing shows up, the page reads 0/0mbs loaded, random page link broken

**Comment by nornagon** [comment]
Can you tell me what browser you're using, including the version?

**Comment by Miami-notgoodwithc** [comment]
chrome, on a chromebook checked on my phone it works

**Comment by nornagon** [comment]
Whoops, missed this response. Can you tell me what version of Chrome? Go to chrome://version to see it. Also, try hard reloading (Ctrl+Shift+R) twice.

**Comment by nornagon** [comment]
I'm assuming this is some sort of transient issue as I haven't heard of this happening to anyone else. Please let me know if you can reproduce it reliably!
