### ISSUE TITLE
Monsters can't be searched by their name, if they get the name via ``copy-from``

### ISSUE THREAD

**Issue by Karol1223** [nornagon/cdda-guide#153]
As in the title. Example is the feral crewman and it's four versions.

The first version, who has a standard defined name in it's JSON, can be searched normally by either ID or the name.

The other three versions, who do not have a name defined in their JSON and instead get it via ``copy-from`` from the first version, can only be searched by their ID.

![image](https://github.com/nornagon/cdda-guide/assets/68503002/544f60fc-dc0b-470b-91c8-4cde1eaa7096)
![image](https://github.com/nornagon/cdda-guide/assets/68503002/a2891b1c-5655-499e-aee1-10f6c57c1979)

**Comment by nornagon** [comment]
Whoops! Good catch. I think this has been a bug for years, can't believe nobody noticed it before! Should be fixed now.
