### ISSUE TITLE
Descriptions do not support `/n` , `</color>` and `<snippet>`

### ISSUE THREAD

**Issue by GuardianDll** [nornagon/cdda-guide#157]
As the title says
![image](https://github.com/nornagon/cdda-guide/assets/67688115/62afbeee-4227-4609-9f7e-052aaa4bd2af)
![image](https://github.com/nornagon/cdda-guide/assets/67688115/bbc04b6e-9d63-479f-8749-30ddd87983e5)
------
![image](https://github.com/nornagon/cdda-guide/assets/67688115/8586f605-8f24-430a-8785-26ef02b9775c)
![image](https://github.com/nornagon/cdda-guide/assets/67688115/5741af4d-5fea-4386-9e2d-a1854cec2f1f)
------
Both are not significant in any way, but should be noted at least

**Comment by nornagon** [comment]
Color is now supported and newlines are respected. Snippets such as <dog_name> or <name_g> aren't supported because I don't think it quite makes sense to do so (as it will change for each item, in the case of <dog_name>, or depending on the player's name in game, in the case of <name_g>).
