### ISSUE TITLE
Addictions for multiple types

### ISSUE THREAD

**Issue by tjlaxs** [nornagon/cdda-guide#159]
There seems to be a minor bug in parsing the addictions for items. For example the **irish_coffee** will now have multiple addictions **coffee** and **alcohol**, but the cdda-guide seems to be waiting for different format for the entries.

There currently are for one addiction format:
```javascript
{
"addiction_type": "alcohol",
"addiction_potential": 15
}
```
And for multiple addictions the format is:
```javascript
{
"addiction_potential": 15,
"addiction_type": [ "amphetamine", { "addiction": "opiate", "potential": 10 } ]
}
```

Look at: https://github.com/CleverRaven/Cataclysm-DDA/blob/011cbe9b43ba34bdbfe0024d8dfcd64b52125583/data/mods/TEST_DATA/items.json#L1752

**Comment by nornagon** [comment]
This was caught by our tests when the usage of this new form was added, 3 days ago: https://github.com/nornagon/cdda-guide/actions/runs/6910884119/job/18804673412
