### ISSUE TITLE
documentation request: how to get a local copy for offline use without installing as pwa

### ISSUE THREAD

**Issue by esotericist** [nornagon/cdda-guide#16]
this came up on the development discord that in the description for the guide, you advertise you can make an offline copy, but don't give instructions for how to do this.

i originally assumed the person was asking about installing it, but you mention installing as a separate thing from an offline copy

in my tests i wasn't able to determine how to make a local copy of the guide that actually functions. it'd be nice if there was something to indicate how to do that on at least the popular browsers

**Comment by natovan** [comment]
Unplug internet and try browsing it. It should work.

**Comment by nornagon** [comment]
The offline copy is made automatically when you load the app. You don't need to install it as a PWA for offline to work. It should work in all modern browsers.
