### ISSUE TITLE
``proportional`` and ``replace_materials`` fields do not appear to be supported

### ISSUE THREAD

**Issue by Karol1223** [nornagon/cdda-guide#163]
As the title says, it appears that HHG does not take these fields into account at all when displaying information about items.

This can be easily seen with ``rapier_fake``, which displays the same stats as ``rapier``, despite the two having different JSON under the hood.

```{
    "id": "rapier_fake",
    "copy-from": "mc_rapier",
    "type": "TOOL",
    "name": { "str": "rapier" },
    "description": "A blunted, cheap replica of a thin sword with an ornate handguard.  It looks like the preferred weapon of gentlemen and swashbucklers.  Light and quick, it makes any battle a stylish battle.",
    "replace_materials": { "mc_steel": "aluminum", "leather": "nylon" },
    "proportional": { "melee_damage": { "bash": 3, "stab": 0.071 }, "price": 0.05, "price_postapoc": 0.05 },
    "delete": { "flags": [ "DURABLE_MELEE" ] },
    "extend": { "flags": [ "FRAGILE_MELEE" ] }

**Comment by nornagon** [comment]
`proportional` is partially handled, see below. but looks like we missed `melee_damage`, i'll add that in :) and you're right, `replace_materials` isn't handled at all yet. https://github.com/nornagon/cdda-guide/blob/fa4adfa44a835038f9b30b6f1780a1d00c22cb92/src/data.ts#L452-L496

**Comment by RenechCDDA** [comment]
Do you want a new open issue for the proportional stuff? Was discussing biosilcified chitin armor, which copies from normal 'chitinous armor' with a proportional 1.5 encumbrance but HHG displayed both as having the same.

**Comment by nornagon** [comment]
Yes please, & it’s super useful to be specific about what you see that’s not working as we do support some proportional stuff already
