### ISSUE TITLE
Showing vitamins either always as % or as both % and weight when the weight is defined in JSON

### ISSUE THREAD

**Issue by Karol1223** [nornagon/cdda-guide#168]
So currently if a comestible has vitamin defined by weight in the JSON, HHG shows it in weight units. Ingame it's shown in both weight and % alongside one another. It'd be handy if we could use HHG to see how the weight translates to % without opening the game (or... I mean, calculating it by hand. Yes, I am lazy)

**Comment by nornagon** [comment]
Cleaned this up a bit, let me know if you see any inconsistencies! Found https://github.com/CleverRaven/Cataclysm-DDA/issues/74840 along the way.

**Comment by Karol1223** [comment]
> Cleaned this up a bit, let me know if you see any inconsistencies! Found [CleverRaven/Cataclysm-DDA#74840](https://github.com/CleverRaven/Cataclysm-DDA/issues/74840) along the way.

Yeah, I am pretty sure something isn't right...

![image](https://github.com/nornagon/cdda-guide/assets/68503002/d4926cad-f777-4e09-af85-670b5d5fa7cc)

**Comment by nornagon** [comment]
Whoops, what item is that?

**Comment by Karol1223** [comment]
> Whoops, what item is that?

An apple

**Comment by nornagon** [comment]
Thanks for the catch, should be fixed now :)
