### ISSUE TITLE
[Feature request] OpenSearch Manifest

### ISSUE THREAD

**Issue by Djent-** [nornagon/cdda-guide#169]
OpenSearch is a way for a website to advertise to users' browsers that a field provides a search engine functionality. This would be useful so users (like me) could add Hitchhiker's Guide as a built-in search engine to their browsers, following the instructions https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox

Implementation would require modifying the template OpenSearch XML manifest file and adding a `<link ...` to it in the webpage `<head>`, as explained in the documentation below:
https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by nornagon** [comment]
Yeah, this is a good idea, I'll add it!

**Comment by Djent-** [comment]
Thanks nornagon for the fast response! I saw you added a few commits addressing OpenSearch last night. For me (tried using Firefox and Chromium) it still doesn't work correctly, for some combination of the following reasons:
- due to the cached nature of the site, `/opensearch.xml` will try to load from cache, where it doesn't exist
- `/opensearch.xml` is served with `Content-Type: application/xml` instead of `Content-Type: application/opensearchdescription+xml`
- the `<link ...` does not include a `title="..."` which should be identical to the `ShortName` in the xml file

**Comment by nornagon** [comment]
Regarding the caching, I don't think the browser will go through the service worker to fetch /opensearch.xml. So I don't believe that's an issue, though if you have evidence to the contrary I'm interested to see it!

As for the other two issues, hopefully 8c8913b24710fbfddef8730bcb4cb2fb5cdb4267 clears them up.

**Comment by Djent-** [comment]
Adding the search engine to browsers works correctly now.

However, searching using the search engine doesn't work.
- `opensearch.xml` specifies `template="https://cdda-guide.nornagon.net/{searchTerms}"` when it should point to `https://cdda-guide.nornagon.net/search/{searchTerms}`
- the search engine does not URL decode `+` into spaces, so multi-word searches doesn't work

**Comment by nornagon** [comment]
Ah, thanks for pointing those out! 🤦🏻 

The template should be fixed with 1c36660, but I'm not exactly sure what to do with the `+` issue. Chrome seems to encode spaces as %20, which works correctly. If you type e.g. `+P` into the search box, Chrome resolves that to `https://cdda-guide.nornagon.net/search/+P`, which correctly searches for overpressure ammo. If I decode `+` as space, then this won't work correctly in Chrome :/

**Comment by nornagon** [comment]
2126188 is an attempt to handle the conflict gracefully, let's see how that goes.

**Comment by Djent-** [comment]
Looking forward to testing the search again once it goes live.

We are definitely in the bowels of Firefox's implementation details. It appears the question of "plus encoding", which is used for `application/x-www-form-urlencoded` vs "percent encoding", which is what the URL RFC describes has been known for a while by Mozilla https://support.mozilla.org/mk/questions/1396405

**Comment by nornagon** [comment]
It should already be live. I had to remove and re-add the search engine in Chrome for it to update, but it seems to be working. Unfortunately I was correct that searching for "+P" through the search plugin ends up searching for " P" in Chrome, not sure how it's going in Firefox. I guess I could test the UA, but that feels like such a hack!

**Comment by Djent-** [comment]
It all seems to work in Firefox! HHG understands that `+` is a space, Firefox percent encodes `+` to `%2B` which searches for over-pressured ammunition correctly. It is a bummer that this caused a regression for Chromium-based browsers since that's what most of the internet is using.

Checking the User-Agent probably is the way to go for this situation. Short of using a purpose-built User-Agent categorization library, looking for `like Gecko` is a good way to separate out the non-Firefox from the Firefox. I too wish we could move on from the days of checking User-Agent strings though

The last major desktop browser to test would be Safari, which I don't have a good way to help with. We can presume Safari's behavior falls into either Chrome's or Firefox's.
