### ISSUE TITLE
Changes "items": "chance" field now to defaults to 100 in 100 rather than 1 in 100

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#172]
It appears the interpretation of itemgroup entries that do not explicitly specify chance has changed. See https://github.com/CleverRaven/Cataclysm-DDA/pull/72458. cdda-guide may need an audit to make sure this case is consistent with how the game handles it.

**Comment by nornagon** [comment]
oof, that's a rough change, thanks for bringing it to my attention.

fortunately(?), I think HHG has been incorrect until now, and that PR brings CDDA in line with HHG 😁 I, too, must have assumed that the default was to spawn the item 100% of the time.
