### ISSUE TITLE
Materials incorrect when `replace_materials` is present

### ISSUE THREAD

**Issue by Drew4484** [nornagon/cdda-guide#173]
Items that use "replace_materials" do not reflect the replaced materials, showing the original item's values. 
<https://cdda-guide.nornagon.net/item/armor_lc_heavyplate> and <https://cdda-guide.nornagon.net/item/armor_qt_heavyplate> show the material as "Low Carbon Steel" and show the defensive values appropriate for that material, not the "Tempered Steel" that should appear. This can be replicated on any items that use "replace_material". 
![image](https://github.com/nornagon/cdda-guide/assets/57647637/04f256dc-c10f-45c6-bd07-5b5eda6dd645)
![image](https://github.com/nornagon/cdda-guide/assets/57647637/69d82bfd-0a0e-4bdc-8f29-6ded68fb6262)

**Comment by nornagon** [comment]
Thanks for the report, this should be fixed now (assuming the tests pass). There are still some remaining bugs with replace_materials—e.g. item weight isn't properly updated—but it should at least have the correct materials in the material list and the armor data!
