### ISSUE TITLE
FEMA camp ammos avg.count is wrong

### ISSUE THREAD

**Issue by ShuCuoMao** [nornagon/cdda-guide#176]
![image](https://github.com/user-attachments/assets/a54a5905-6249-4d18-91d7-3aaa00b99791)
it shows a fema camp will generate 500 m855a1 bullets ,but actually fema camp's item spawn is "milspec_guns&ammo_or_leftovers" and it wont generate that many.
![44XY%~}~8OHC3J HTVAD28E](https://github.com/user-attachments/assets/1da5b134-4d61-4b4d-bb4e-ea4f34eb3a02)
In game test its item generate is like this 
![image](https://github.com/user-attachments/assets/6b429c87-10a2-4c81-90b7-fd71648eb5f4)
most of the cans empty and it wont generate 500 m855a1 bullets in avg

**Comment by ShuCuoMao** [comment]
my version is latest till now,but in guide former versions with FEMA camp display the wrong number as well

**Comment by nornagon** [comment]
Reopening as this seems like probably a real bug!

**Comment by ShuCuoMao** [comment]
> Reopening as this seems like probably a real bug!

I thought it's just my fault that I had a bad luck and count it wrong,so I closed it the next day sorry

**Comment by nornagon** [comment]
As a data point, I just spawned a FEMA camp in debug mode and stripped all the ammo. I found 120 x 5.56 NATO M855A1, which is quite a bit lower than the expected count, so it seems fairly likely that there's a real bug here.

**Comment by ShuCuoMao** [comment]
> As a data point, I just spawned a FEMA camp in debug mode and stripped all the ammo. I found 120 x 5.56 NATO M855A1, which is quite a bit lower than the expected count, so it seems fairly likely that there's a real bug here.

Has it been solved?
