### ISSUE TITLE
The default ``to-hit`` syntax is wrong

### ISSUE THREAD

**Issue by Karol1223** [nornagon/cdda-guide#181]
As of https://github.com/CleverRaven/Cataclysm-DDA/pull/74597 the default ``to-hit`` is -2, as it was supposed to be. It appears that currently HHG still believes it to be 0, as displayed on the soldering iron page.

**Comment by sonphantrung** [comment]
Eh? I see to-hit as -3 in soldering iron page.

**Comment by Karol1223** [comment]
> Eh? I see to-hit as -3 in soldering iron page.

I have audited it in the repo since this issue was opened. You have to look at the experimental versions from the day this was posted.

**Comment by nornagon** [comment]
Changed with https://github.com/CleverRaven/Cataclysm-DDA/pull/74597
