### ISSUE TITLE
Monster difficulty calculation has changed

### ISSUE THREAD

**Issue by RenechCDDA** [nornagon/cdda-guide#182]
Basically some special attacks got whitelisted to not count.

https://github.com/nornagon/cdda-guide/blob/b64a93099775e835090d72238aed154a36489505/src/types/Monster.svelte#L71-L76

Compare to master:

https://github.com/CleverRaven/Cataclysm-DDA/blob/348453333a599a0afbb829acfa145e9bc63a7ccc/src/monstergenerator.cpp#L380-L393

Related PRs: 
https://github.com/CleverRaven/Cataclysm-DDA/pull/75716
https://github.com/CleverRaven/Cataclysm-DDA/pull/75804

**Comment by nornagon** [comment]
awh, pr would have been nice! thanks for the detailed references.
