### ISSUE TITLE
Obtaining -> LOOT section doesn't work

### ISSUE THREAD

**Issue by DSeyka** [nornagon/cdda-guide#183]
Regardless of item in question and browser used (tried Firefox, Chrome and Edge), I'm getting this (it's not actually loading anything, best I can tell):
![image](https://github.com/user-attachments/assets/1ba916a0-0487-494e-86d5-86eefc602d61)
The screenshot above is from the link https://cdda-guide.nornagon.net/item/22_blank but again, I'm getting this for any item.

**Comment by nornagon** [comment]
Huh, it’s working for me… are there any errors in your console?

**Comment by DSeyka** [comment]
Nevermind, I just had to wait for about a minute. I guess it WAS loading stuff after all!
Is it possible to put a progress indication of some kind there?

**Comment by nornagon** [comment]
Yeah, a progress indicator would make sense. It’s CPU work that it’s doing
to compute all the loot tables, but it’s usually a few seconds for me (even
on my phone). Are you loading it on a raspberry pi or something…?


j

**Comment by DSeyka** [comment]
No, it's a PC (Ryzen 5 5600X).
Just tried it on my phone (realme Note 50) and it takes about the same amount of time to load.

**Comment by nornagon** [comment]
Wow okay I just timed this for myself and got 23 seconds on my M3 macbook pro... i feel like this used to be much faster, I'll look into it.

**Comment by nornagon** [comment]
not sure exactly what changed here but i tweaked it and it should be quite a bit faster now. down to ~5 sec on my machine.

**Comment by DSeyka** [comment]
Yep, it loads way faster in Chrome and Edge for me now, no change in Firefox.
