### ISSUE TITLE
The weight of XL steel-plated Kevlar jumpsuit is wrong

### ISSUE THREAD

**Issue by cknight828** [nornagon/cdda-guide#185]
The weight of XL steel-plated Kevlar jumpsuit is 10734.999999999998 g(10.73 kg) in game, but 1000000000.00 kg in guide.
https://cdda-guide.nornagon.net/item/xl_hsurvivor_jumpsuit

**Comment by nornagon** [comment]
wow, that's _quite_ wrong

**Comment by nornagon** [comment]
oh, the data for this in the json files is wrong, CDDA doesn't support floats in that field. HHG should interpret this better but this is a data issue.

**Comment by nornagon** [comment]
ohhh wait it's because of `proportional`. nvm, yes this is my bug :D
