### ISSUE TITLE
Documenting offline usage

### ISSUE THREAD

**Issue by harakka** [nornagon/cdda-guide#22]
Hi,
the readme mentions that 

> "The Guide stores all its data locally and is offline-capable, so you can take it with you whereever you go. It's also installable, so you can pop it out of your browser like a regular app."

 Could you add instructions for how to use the guide offline/install it locally? This gets asked on the CDDA Discord occasionally.

**Comment by nornagon** [comment]
Ah sure, there's actually nothing to do to use it offline. Just visit the page while you're offline, it works fine. Literally turn off WiFi and type the URL into the browser. You can "install" it as a PWA if you want, but that's not required to use it offline.

I guess I can write something about that in the readme.
