### ISSUE TITLE
The guide can't show items currently

### ISSUE THREAD

**Issue by Broken27** [nornagon/cdda-guide#23]
Items pages don't load.

Furniture and monster pages work normally.

**Comment by nornagon** [comment]
@Broken27 Yeah, it looks like some changes upstream caused parsing issues. The tests caught it, but I didn't have time to fix it until yesterday. It should be good now though, take another look? If it doesn't work straight away, you might need to hard-refresh (<kbd>Cmd+Shift+R</kbd> / <kbd>Shift+F5</kbd>)
