### ISSUE TITLE
SImply not working

### ISSUE THREAD

**Issue by jorganmir** [nornagon/cdda-guide#26]
The browser doesn't seem to correctly show any results for anything. When initially opened, the browser can search for items correctly, but trying to click on items for more info pulls up a blank page. After this, even clicking the banner at the top doesn't bring one to the initial page.

**Comment by hexagonrecursion** [comment]
Fixed by 826b16a. This should be closed.

**Comment by nornagon** [comment]
thanks for the reports friends!
