### ISSUE TITLE
How do I get unifont.woff ?

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#27]
I cloned the repo and ran `yarn dev`, but without `unifont.woff` in `./public` all I see is a blank page

**Comment by nornagon** [comment]
it's from cdda itself: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/font/unifont.ttf, converted to woff with https://cloudconvert.com/ttf-to-woff.

Not sure I want to add it directly to the repo because it's quite large, but maybe it's worth doing.

**Comment by hexagonrecursion** [comment]
I have submitted a request to add GNU Unifont to fontsource https://github.com/fontsource/fontsource/issues/322 . If I understand correctly this should allow us to get it via npm

**Comment by nornagon** [comment]
Ah, cool! Thanks, yeah that would likely work. Let me know how it goes.

**Comment by hexagonrecursion** [comment]
https://github.com/fontsource/fontsource/issues/322#issuecomment-913227563:

> You can find it at @fontsource/unifont now! Thanks for waiting!

**Comment by nornagon** [comment]
@hexagonrecursion thanks! It took me a while to figure out how to properly copy the font files into the build directory (probably should just have done a regular old `cp` in `postinstall`, but it's done now...) fixed in ad87cf2ed528d0a5ab635a87886d1bd09c9777b7.
