### ISSUE TITLE
Items that extend a base item do not apply the "delete qualities" fields

### ISSUE THREAD

**Issue by cheewooisaw** [nornagon/cdda-guide#34]
E.g., the [steel frying pan](https://nornagon.github.io/cdda-guide/?v=0.F-2#/item/steel_pan) has both level 3 and level 2 food cooking quality. Presumably because after extending from base_cookpot, it doesn't delete the COOK 3 quality. It does apply the extend COOK 2 quality though.

Relevant excerpts from dining_kitchen.json:
```
  {
    "abstract": "base_cookpot",
    ...
    "qualities": [ [ "COOK", 3 ], [ "BOIL", 2 ], [ "CONTAIN", 1 ], [ "CHEM", 1 ] ],
  },

  {
    "id": "steel_pan",
    "name": { "str": "steel frying pan" },
    "copy-from": "base_cookpot",
    ...
    "delete": { "qualities": [ [ "COOK", 3 ] ] },
    "extend": { "qualities": [ [ "COOK", 2 ] ] }
  }
```

Addtionally linked to this, the [food cooking tool quality page](https://nornagon.github.io/cdda-guide/?v=0.F-2#/tool_quality/COOK) lists the steel frying pan as a level 3 food cooking item when it is only level 2 (though, I assume this will be fixed automatically once the base issue is fixed)

**Comment by nornagon** [comment]
Thanks for the report! Looks like my delete logic doesn't cover this case. https://github.com/nornagon/cdda-guide/blob/91602b56fa05a2d82f2eeb30b52f1183a8f73b53/src/data.ts#L262-L266

Should be fixed now!
