### ISSUE TITLE
FIT flag for item directory

### ISSUE THREAD

**Issue by fairyarmadillo** [nornagon/cdda-guide#41]
Some items in the directory e.g. [https://nornagon.github.io/cdda-guide/#/item/jacket_leather_tire](https://nornagon.github.io/cdda-guide/#/item/jacket_leather_tire) are displaying encumbrance values for when they don't fit - that armor should show 10 encumbrance, not 20. This makes the listed encumbrance values confusing and inaccurate to what you'd get in the game if you found a piece that fit, or crafted it, or repaired a piece. Since not all items that have encumbrance even use the FIT flag it's unclear when looking at the guide whether the numbers are accurate.

It sounds annoying to program, but I suggest figuring out a way to make it so all items are shown with their FIT encumbrance values just for clarity's sake, or perhaps include a toggle so that people can see it either way.

**Comment by nornagon** [comment]
Looks like this is the formula for FIT, which is only relevant when VARSIZE is also present:

```
    if( has_flag( flag_FIT ) && has_flag( flag_VARSIZE ) ) {
        encumber = std::max( encumber / 2, encumber - 10 );
    }
```

It seems reasonable to show the values for clothing that fits, though I'll spend a bit of time thinking about whether it might be better to show both values (i.e. for `(fits)` and for `(poor fit)`) than to just show the FIT value.

**Comment by coyo7e** [comment]
Could it be doable to add a flag to "this might not always fit!" for items that are able to be badly fitted, rather than calculating on every instance? Being unable to easily wear an "un-fitted" item is not something I've ever wanted to look up the encumbrance of in advance, it's more of a "yes, no" thing to my mind but I may just me in the minority.

**Comment by nornagon** [comment]
This is finally done :)

<img width="522" alt="Screen Shot 2023-06-14 at 10 19 39 PM" src="https://github.com/nornagon/cdda-guide/assets/172800/61bbf3ed-493a-4281-974f-c1a042098b63">
