### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by d1ssolvedz** [nornagon/cdda-guide#42]
Hello. Is there a way to change locale of the guide? I have troubles with english so it would be cool if i can somehow change it to other language, that i actually use ingame.

**Comment by nornagon** [comment]
This has occurred to me and I'd love to offer the ability to change language! It is technically not too difficult, but would require changes to https://github.com/nornagon/cdda-data to start collating and archiving the locale data in addition to the JSON to start with.
