### ISSUE TITLE
List weapons by category

### ISSUE THREAD

**Issue by Terrorforge** [nornagon/cdda-guide#43]
The item list is obviously great for finding out about a particular weapon, but I often find myself wanting to approach from the other direction. E.g. I want to look at every pistol, or every 5.56 rifle. It would be great if each weapon listed certain categories it belonged to, and if those categories had pages listing the relevant weapons, just like materials or mutation categories work currently. The relevant categories I can think of are:

- Martial arts "weapon_category"
- Weapon skill/type (pistol, smg, rifle, etc.)
- Ammo type(s)

These should also be visible and linked on the weapon's page and, in the case of weapon_category, on the various martial arts pages as well. Those could probably stand to list every weapon they include, actually.

(Thanks for adding martial arts, btw. That was starting to get real hard to keep track of.)

**Comment by nornagon** [comment]
For ammo type, it would make sense to amend the `ammunition_type` page to list compatible weapons, e.g. https://nornagon.github.io/cdda-guide/#/ammunition_type/223.

Adding a `weapon_category` listing page would be reasonable. (Though the categories seem to be in all-uppercase in the JSON? https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/weapon_categories.json

And listing weapons that require a given skill on skill pages is also a reasonable addition, e.g. https://nornagon.github.io/cdda-guide/#/skill/smg

So yeah I think all that is doable!

**Comment by nornagon** [comment]
looks like weapon_category is a pretty new thing! martial arts used to list all the compatible weapons, which the Guide supported (e.g. see this experimental from a few months ago, which lists out all the weapons individually: https://nornagon.github.io/cdda-guide/?v=cdda-experimental-2021-09-14-0610#/martial_art/style_eskrima). But it was changed basically immediately after I added it 😭

In any case, we support both now.

Also, all done on this issue 👍  let me know if you see any problems.

**Comment by Terrorforge** [comment]
Yeah, they were added in recent months because it's kind of precarious from a development standpoint to manually add each new weapon to each martial arts. More sensible to fit them into categories.

I don't see any problems, stellar work as always!
