### ISSUE TITLE
No baseballs in the baseball field

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#44]
* Empirically: the baseballs do spawn in a baseball field.
* https://nornagon.github.io/cdda-guide/#/item/baseball does not even list this as a loot location.

https://github.com/CleverRaven/Cataclysm-DDA/blob/9539ea9c7ad8910f32e6291eef8cbda7b2206904/data/json/mapgen/field_baseball.json#L63
```json
      "place_loot": [
        ...
        { "item": "baseball", "x": [ 1, 21 ], "y": [ 31, 46 ], "chance": 90 }
      ],
```
Unfortunately I am *unlikely* to get around to debugging this any time soon.

**Comment by nornagon** [comment]
It was because the code for slicing up multi-tile mapgens didn't understand coordinate ranges :)
