### ISSUE TITLE
Add support for obtaining items from nested mapgens

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#45]
[purifier_smart_shot](https://nornagon.github.io/cdda-guide/#/item/purifier_smart_shot) currently has no "obtaining" section. It looks like it only spawns in nested mapgens.

```sh
$ fgrep -r _smart_shot src/ data/
data/json/items/comestibles/mutagen.json:    "id": "purifier_smart_shot",
data/json/mapgen/lab/lab_modular/lab_nests_modular/lab_nested_mutagen.json:        { "item": "purifier_smart_shot", "x": 5, "y": 1, "chance": 100 },
data/json/mapgen/lab/lab_modular/lab_nests_modular/lab_nested_mutagen.json:        { "item": "purifier_smart_shot", "x": 5, "y": 6, "chance": 100 }
data/json/mapgen/lab/lab_floorplans_finale1level.json:      "mapping": { "r": { "item": [ { "item": "purifier_smart_shot", "chance": 100 } ] } },
data/mods/No_Hope/Mapgen/lab_floorplans_finale1level.json:      "mapping": { "r": { "item": [ { "item": "purifier_smart_shot", "chance": 100 } ] } },
```

**Comment by nornagon** [comment]
Thoughts about how to handle probabilities for such spawns?

**Comment by nornagon** [comment]
I've made a start on this: https://github.com/nornagon/cdda-guide/tree/nested-mapgens

Currently I plan to ignore the "neighbors" and "else_chunks" sections because I don't think there's any sane way to handle them.

**Comment by nornagon** [comment]
NB, this is merged but `purifier_smart_shot` still shows no obtaining section because the locations it appears in (lab_mutagen_6_level, Lab_MUTAGEN_2x2x2) are either explicitly hidden or don't have any appearance at Z=0 https://github.com/nornagon/cdda-guide/blob/47a8ec687eb871fcbb49be557c1ce657ec5f01e3/src/types/item/spawnLocations.ts#L180-L188
