### ISSUE TITLE
Displaying the caly lump data fails

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#47]
https://nornagon.github.io/cdda-guide/?v=cdda-experimental-2021-12-31-0454#/item/clay_lump

> There was a problem displaying this page. Not all versions of Cataclysm are supported by the Guide currently. Try selecting a different build.
>
> too much recursion

**Comment by ccaviness** [comment]
Some upstream change is causing this failure, and for most (all?) items.
Using `cdda-experimental-2021-12-30-0612` works, but all versions after that (starting at `cdda-experimental-2021-12-30-0730`) fail with the `Maximum call stack size exceeded` error.

Presumably this means something [here](https://github.com/CleverRaven/Cataclysm-DDA/compare/cdda-experimental-2021-12-30-0612...cdda-experimental-2021-12-30-0730) is causing the issue, but I can't see what it would be.

**Comment by nornagon** [comment]
It's because this recipe copies from the other version of a recipe for the same item: https://github.com/CleverRaven/Cataclysm-DDA/blob/c02d868259bffe65a9e9a50dd750fbe4de831517/data/json/recipes/armor/head.json#L1833-L1835

We need to munge recipe IDs better, I think.
