### ISSUE TITLE
Support construction byproducts

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#48]
The guide is currently missing information on how to obtain a lump of clay https://nornagon.github.io/cdda-guide/#/item/clay_lump

We should parse this:
https://github.com/CleverRaven/Cataclysm-DDA/blob/b757057ad12a9044424691b4a0476d1e172cd1ec/data/json/construction.json#L3259-L3271

**Comment by nornagon** [comment]
"extract clay" is theoretically derivable from JSON: https://github.com/CleverRaven/Cataclysm-DDA/blob/b757057ad12a9044424691b4a0476d1e172cd1ec/data/json/construction.json#L3259-L3271

In general I want the Guide to be purely exposing data from the JSON, and also generally exposing _functional_ data, not e.g. comments written in the JSON (as the comments can be and often are out of date). The way to get this sort of thing into the Guide is to refactor the game itself to move whatever should be in the Guide into the JSON :)

**Comment by hexagonrecursion** [comment]
I have updated the issue description
