### ISSUE TITLE
Support power tools

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#49]
Some tools provide qualities only when they are powered. One example is a cordless drill:

https://github.com/CleverRaven/Cataclysm-DDA/blob/8a7f59568aba671c39dd1247abef909ddddf7993/data/json/items/tool/workshop.json#L288-L317

```json
    "charges_per_use": 5,
    "qualities": [ [ "SCREW", 1 ] ],
    "charged_qualities": [ [ "DRILL", 3 ] ],
```

The guide does not currently report that:
https://nornagon.github.io/cdda-guide/#/tool_quality/DRILL

**Comment by nornagon** [comment]
Thanks! Looks like this was recently added :)
