### ISSUE TITLE
Salvage incorrectly shows leather wallet

### ISSUE THREAD

**Issue by ChucklesTheBeard** [nornagon/cdda-guide#50]
1. https://nornagon.github.io/cdda-guide/#/item/leather
2. Expand list under "Salvage"
3. ctrl+f "leather wallet"

In-game, the leather wallet isn't able to be cut up because it weighs less than a leather patch.

**Comment by nornagon** [comment]
Eagle-eyed! Should be fixed. Thanks for the report.
