### ISSUE TITLE
Ammunition is displaying incorrectly

### ISSUE THREAD

**Issue by Terrorforge** [nornagon/cdda-guide#51]
Many types of ammunition are displaying the incorrect values. Specifically, every version of a particular kind of ammunition tends to display the damage, penetration, etc. of the base type. As an example, compare the three different types of 5x50mm ammo:

https://nornagon.github.io/cdda-guide/#/item/5x50dart
https://nornagon.github.io/cdda-guide/#/item/reloaded_5x50dart
https://nornagon.github.io/cdda-guide/#/item/5x50heavy

They all display as 20 damage and 30 pen, but in-game the reloaded has 18 damage, 21 pen, and Penetrator has 25 damage, 50 pen.

This seems to be an issue with how the Guide handles copy-from and the related "relative" and "proportional" fields, which a lot of ammo uses.

**Comment by nornagon** [comment]
Good catch, I've addressed this now. Let me know if you see any other discrepancies in damage values!
