### ISSUE TITLE
Foraging

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#53]
The way to obtaining be balm ans several other items is by foraging bushes. The guide does not currently say that.

https://github.com/CleverRaven/Cataclysm-DDA/blob/ef67fb944299046ec47d70c156630414b4848ae8/data/json/itemgroups/Agriculture_Forage_Excavation/forage.json

**Comment by nornagon** [comment]
Yeah... I thought about this, but currently the item groups for foraging are hard-coded in the c++ and I'd prefer to avoid writing them into the Guide.

https://github.com/CleverRaven/Cataclysm-DDA/blob/388d316c59b0ba34b08d180f3bb574f5b5168e1c/src/activity_actor.cpp#L5485-L5504

Perhaps I'll take a stab at jsonizing this bit of code.

**Comment by coyo7e** [comment]
Oof that makes sense, I would bet that the code is heavily based on skills too kmaybe even forage based profs?) So it may be a pita to provide decent numbers.

Never even thought about it but I can see how it could be a pain to pull up with math that makes "sense" sometimes

**Comment by hexagonrecursion** [comment]
> it may be a pita to provide decent numbers.

It is OK if there are no numbers. Just telling the player that it is possible to get bee balm by foraging bushes in spring, summer and autumn (with a hyperlink to the bush page) would be a big improvement.
