### ISSUE TITLE
Show file name in raw JSON

### ISSUE THREAD

**Issue by Moumix3** [nornagon/cdda-guide#55]
It would be nice to be able to see the directory + file name from which the raw JSONs (recipe + item) have been pulled. If you want to modify something, you know immediately where to find it and you don't have to a do a search on all the json files for the name/id of the item :)

**Comment by nornagon** [comment]
Seems reasonable, the way to do this is to edit the cdda-data script to annotate each object with the file it came from.

That JSON is generated here: https://github.com/nornagon/cdda-data/blob/b365ec9f5aeecbf940198ec4588ef0a02e4eaacb/pull-data.sh#L32

Adding an extra field to each object like `"__src": "data/json/foo/bar.json"` doesn't seem unreasonable. With gzip compression it shouldn't add too much to the download size.
