### ISSUE TITLE
Sprite fallback and fallback item name.

### ISSUE THREAD

**Issue by vetall812** [nornagon/cdda-guide#65]
It would be great to see not only personal sprite for exact item but also "in-game sprite" that can be inherited from "looks like" mechanism.

And if the sprite was inherited then show name (and link) to such parent item.

PS. Right now I'm drawing sprites for items that havent any. And using the guide is sometimes confusing. As it show no sprite for CBMs but they looks like a case with letters in game.

**Comment by nornagon** [comment]
Hm, I think we already follow the "looks_like" link when there's not a sprite for the item?

https://github.com/nornagon/cdda-guide/blob/61de12f3a108f42c1595364cb72b5e625303c25f/src/types/item/ItemSymbol.svelte#L13-L16

So I'm not sure what you're suggesting we do differently 😅 would you be able to give an example?

**Comment by Faalagorn** [comment]
There's definitely something off though, for example: https://nornagon.github.io/cdda-guide/#/item/bio_fuel_cell_gasoline misses graphic on Chibi Ultica, while in game it is shown: 
![screenshot_2022-04-03-182709](https://user-images.githubusercontent.com/4951331/161437922-d8967984-e2b6-4004-8528-2519b8e5fd4e.png)

**Comment by vetall812** [comment]
Same thing with any ammo. (Except Ultica now)

**Comment by nornagon** [comment]
Ah, I think I found it: if an item uses `copy-from` or `abstract`, the game automatically uses that for the `looks_like` value. Should be an easy fix.

**Comment by nornagon** [comment]
This should be fixed now.
