### ISSUE TITLE
Vehicle sprites are not pulled properly

### ISSUE THREAD

**Issue by Faalagorn** [nornagon/cdda-guide#67]
That stemmed from a discussion with [vetall812](https://github.com/vetall812) on CDDA-Tileset discord, it seems that the vehicle sprites aren't pulled properly.

![screenshot_2022-04-03-193811](https://user-images.githubusercontent.com/4951331/161440750-e55d5315-6ff1-4781-800c-fd82ca5303a5.png)
![screenshot_2022-04-03-194010](https://user-images.githubusercontent.com/4951331/161440843-14095f1c-f36b-4f70-8a0e-46b0d5780acb.png)
(regular workbench and one with a battery recharger as items lying on ground; regular one misses the sprite)
![screenshot_2022-04-03-194017](https://user-images.githubusercontent.com/4951331/161440856-9fc22c48-8730-4279-9d92-504059374997.png)
(regular workbench and one with a battery recharger and a regular one as mounted vehicle parts; the second one have a sprite but falls back to red #, different than the one from the item one and the one with recharger uses a sprite from a lying item)

**Comment by nornagon** [comment]
Fixed! Thanks for the detailed report :)
