### ISSUE TITLE
account for obsoletion entries somehow

### ISSUE THREAD

**Issue by esotericist** [nornagon/cdda-guide#68]
it came up today in the official dev discord that the chainsaw lajatang still shows up for 0.F search results as if it was still available, whereas in 0.F it's been moved to `json/items/obsolete.json` and shouldn't still be considered to be 'active'

ideally hhg should either somehow mark obsolete entries or failing that simply omit them from the scanning. given how obsolete entries are defined (otherwise normally in specific files that signal intent to remove in the next cycle), this might require a list of blacklisted file paths?

a quick search through the tree came up with this list of instances:
```
$ find . -name "*obsolet*"
./data/json/itemgroups/obsolete.json
./data/json/items/obsolete.json
./data/json/monstergroups/obsolete.json
./data/json/monsters/obsolete.json
./data/json/obsoletion
./data/json/obsoletion/obsolete_fake.json
./data/json/recipes/recipe_obsolete.json
./data/json/vehicleparts/obsolete.json
./data/json/obsolete.json
./data/json/obsolete_terrains.json
```
(obviously i have omitted the mod entries, since hhg still doesn't seem to touch those)

aside from three exceptions, the obvious pattern appears to be that paths ending in `/obsolete.json` can *probably* be either disregarded, or (if hhg's infrastructure allows it) somehow marked as obsolete in the name of the relevant entry. fwiw, i couldn't see evidence of anything containing `obsolet` in its filename that should be handled as normal data, if you just wanted to go for the nuclear solution. there are two other json files in `./data/json/obsoletion/` but they didn't look pertinent to hhg's featureset.

also hi long time no post, i'm glad this is still here. 😁

**Comment by nornagon** [comment]
Ah, okay then. At least the “obtaining” section should reflect the truth of the matter! I’m a little hesitant to put something that’s not a functional property into the guide. The intent of the guide is to read the data similarly to how the game itself does, with the idea that the guide should match what’s in-game. eg if an item was softly marked obsolete but was still obtainable in game, the guide should show that. Also, you might be playing a save that was ported forward and want to see the stats of an item you have but could no longer obtain.

Perhaps we could mark the page with a warning or something though!

**Comment by nornagon** [comment]
> in principle anything in the obsolete files that's still obtainable in-game is a bug

it is not the guide's place to determine what is or isn't a bug ;) we just faithfully report the data as it is! but it could be useful to know that an item is intended to be obsolete by developers. would it perhaps make sense to change the JSON in the game itself to mark {items,vparts,terrain,monsters,vitamins,etc.} that are obsolete with an `"obsolete": true` flag? this is already the case for recipes, and in fact the guide already reads that flag for recipes. additionally, the game could throw a warning if anything new was spawned that was marked obsolete. in the mean time, we already have a separate issue for adding filename data to the JSON: https://github.com/nornagon/cdda-guide/issues/55, so if we do that then it wouldn't be crazy to add a warning at the top of the page like [⚠️ this item is marked obsolete].



on reporting things that aren't obtainable through some path that's visible to JSON, that's something that I don't think the game's data is at a point yet where we could reasonably flag that and be confident that an item was actually unobtainable. there are quite a lot of special-case mapgens, iuse actions and other C++-mediated interactions that generate items. if at some point in the future it becomes reliable that items are only generated through paths that are traceable in JSON, then I'd consider flagging that more noticeably. It's already visible in the guide currently as the absence of an 'obtaining' section, though.

**Comment by esotericist** [comment]
fair enough on all of that.

**Comment by nornagon** [comment]
Warning added: https://github.com/nornagon/cdda-guide/commit/17c5f4b04025ac7adb3b7768c5d2035bec04cb5a

It will only be present on new versions because I did not backfill the data for #55.
