### ISSUE TITLE
Raw Milk listed as component of plastic

### ISSUE THREAD

**Issue by tpagett** [nornagon/cdda-guide#72]
As the title states, raw milk is listed as a component of plastic. 

https://nornagon.github.io/cdda-guide/#/item/milk_raw

Best guess is it's doing that based on the listed container showing as plastic, but I'm not 100% certain. 

All I know is, milk can't be used to craft plastic.

**Comment by Xtrem532** [comment]
This is no bug, see here: https://www.sciencebuddies.org/stem-activities/milk-into-plastic

You can combine Milk an Vinegar into a plastic chunk in game.

**Comment by nornagon** [comment]
on [the page for plastic_chunk](https://nornagon.github.io/cdda-guide/?v=cdda-experimental-2022-05-18-2327#/item/plastic_chunk):

![Screen Shot 2022-06-01 at 10 12 33 PM](https://user-images.githubusercontent.com/172800/171557418-9477814c-62dd-4471-b768-0d2465bfeb52.png)
