### ISSUE TITLE
Add dissection sources to items' "Obtaining" section

### ISSUE THREAD

**Issue by Terrorforge** [nornagon/cdda-guide#76]
Monster entries show what you can get by dissecting them, but items don't show which monsters they can be dissected out of. E.g. [gigantic naked mole-rat](https://nornagon.github.io/cdda-guide/#/monster/mon_nakedmolerat_giant) shows that dissecting it yields a troglobite sample, but the [troglobite sample page](https://nornagon.github.io/cdda-guide/#/item/troglobite_sample) doesn't tell you it can be acquired by dissecting a gigantic naked mole-rat.

It would be convenient if the item listed dissection sources the same ways they already do list butcher sources.

**Comment by nornagon** [comment]
done! also fixed an issue where `mutagen_group` and other harvest groups weren't properly understood by the guide.
