### ISSUE TITLE
Gun information not populating correctly when relative adjustments are utilized

### ISSUE THREAD

**Issue by Ilurker** [nornagon/cdda-guide#77]
While working to compile a spreadsheet of the current guns and their attributes, I noticed that the HHG entry for player crafted .50 caliber rifle disagreed with the HHG entry. The most consequential departure is in the gun's base damage, with HHG believes is 0 but is actually -4.

On investigation of 50.json, it became apparent that HHG was having difficulty with a combination of both copying the attributes from another JSON entry and relative adjustments, and was not correctly parsing the JSON.

On review, it appears this is the specific block not being picked up:

    "relative": {
      "weight": "-21500 g",
      "volume": "-1500 ml",
      "price": -1210000,
      "ranged_damage": { "damage_type": "bullet", "amount": -4 },
      "dispersion": 60,
      "barrel_volume": "-250 ml"
    },
    "blackpowder_tolerance": 24,
    "longest_side": "130 cm",
    "flags": [ "RELOAD_EJECT" ],
    "pocket_data": [ { "pocket_type": "MAGAZINE", "rigid": true, "ammo_restriction": { "50": 1 } } ]

**Comment by nornagon** [comment]
Thanks for the report! Should be fixed now.
