### ISSUE TITLE
Separation of Clothing and Armor

### ISSUE THREAD

**Issue by Sniper27IT** [nornagon/cdda-guide#82]
In the Item menu currently all clothing items are grouped in the armor tab. I think that it would be nice and better-readable if clothing apparel and armor are separated in 2 distinct tabs, just as the game does with "clothing" and "armor" categories.
Still, thanks for the huge work on the guide, it has become the first source of information about the game thanks to its ability to read directly the game code and being able to update as fast as the game.

**Comment by nornagon** [comment]
Hm, how do you tell from the data what is "clothing" and what is "armor"?

**Comment by nornagon** [comment]
Alrighty, this is done! It does make the items page a lot more useful, I think. Thanks for the idea :)
