### ISSUE TITLE
Items can be obtained by [a]ctivating other items

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#86]
While testing https://github.com/CleverRaven/Cataclysm-DDA/issues/59639 I was puzzled as to how am I supposed to obtain a soaked_dandelion. https://nornagon.github.io/cdda-guide/#/item/soaked_dandelion currently does not tell us how to obtain it.

It turns out that I need to craft a soaking_dandelion, wait, and [a]ctivate it.

[Here it is in json](https://github.com/CleverRaven/Cataclysm-DDA/blob/ea157f552514cb1adc5dca6dbaadfe97b7a1c600/data/json/items/comestibles/brewing.json#L655-L682)

**Comment by hexagonrecursion** [comment]
@nornagon thank you

**Comment by nornagon** [comment]
np!
