### ISSUE TITLE
[Feature Request]: Random page

### ISSUE THREAD

**Issue by NinaTur** [nornagon/cdda-guide#88]
How about adding a random page to the site? (this will help for some scenarios)

**Comment by nornagon** [comment]
Do you mean like, a button to go to a random item/monster/terrain/etc.?

**Comment by NinaTur** [comment]
Yes, that would be a very good opportunity for many players.

**Comment by Nina667** [comment]
A random page always yields condensed milk
![Uploading IMG_20220903_030201.jpg…]()
