### ISSUE TITLE
Add brewing

### ISSUE THREAD

**Issue by Cimanyd0** [nornagon/cdda-guide#90]
> [Every item type can have optional brewing data, if the item has brewing data, it can be placed in a vat and will ferment into a different item type.
](https://github.com/CleverRaven/Cataclysm-DDA/blob/49aa880e6357c134a77a13391eaa21e7b911f193/doc/JSON_INFO.md#brewing-data)

Similar to #86, this leaves a gap in the guide where you have to look in the raw JSON to see, for example, [curdling milk](https://nornagon.github.io/cdda-guide/#/item/brew_milk_curdled) > [curdled milk](https://nornagon.github.io/cdda-guide/#/item/milk_curdled).

**Comment by nornagon** [comment]
Thanks for the suggestion! Should be in now :)
