### ISSUE TITLE
Sprite from HollowMoon not displaying properly

### ISSUE THREAD

**Issue by Fris0uman** [nornagon/cdda-guide#92]
As an exemple the boomer appears as fallback while in game it does have a sprite

It's likely caused by HollowMoon sprite all being seasonal variant, meaning they all have a `id_season_<season_name>`

In guide
![image](https://user-images.githubusercontent.com/41293484/185417372-1eee160c-98f9-4375-a7ba-7db380905c29.png)

In game
![image](https://user-images.githubusercontent.com/41293484/185417519-a03ada40-8707-46ac-b232-b26471f89c5b.png)

**Comment by secretstamos** [comment]
Would be greatly helpful if this was fixed

**Comment by nornagon** [comment]
thanks for the report! should be fixed with 5002b63.
